# Generated by Django 5.0.3 on 2024-11-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='closing_stock',
            field=models.IntegerField(default=0),
        ),
    ]
