# Generated by Django 5.0.3 on 2024-12-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myInventory', '0003_inventory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='closing_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_updated',
        ),
    ]
